language: python

python: "2.7.14"

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - pip install -r requirements.txt
  - python --version
  - pylint --version

script:
  - make ut_test
  - make ac_test
  - make lint
