language: python

python: "2.7"

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - pip install pyparsing
  - pip install pylint

script:
  - make ut_test
  - make ac_test
  - make lint
